[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-fps", "60", "--transition-step", "255", "--transition-type", "center"]
set = false

[templates.hyprland]
input_path = './templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors/matugen.conf'
post_hook = 'hyprctl reload'

[templates.waybar]
input_path = './templates/colors.css'
output_path = '~/.config/waybar/colors/matugen.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.rofi]
input_path = './templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors/matuegen.rasi'

[templates.swaync]
input_path = './templates/colors.css'
output_path = '~/.config/swaync/colors/matugen.css'
post_hook = 'swaync-client -R && swaync-client -rs'

[templates.wlogout]
input_path = './templates/colors.css'
output_path = '~/.config/wlogout/styles/matugen.css'

[templates.kitty]
input_path = './templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors/matugen.conf'
post_hook = 'pkill -SIGUSR1 kitty'

[templates.starship]
input_path = './templates/starship-colors.toml'
output_path = '~/.config/starship.toml'

[templates.pywalfox]
input_path = './templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.vesktop]
input_path = './templates/midnight-discord.css'
output_path = '~/.config/Vencord/themes/midnight-discord.css'

# Gtk3
[templates.gtk3]
input_path = '~/.config/matugen/templates/matugen-gtk.css'
output_path = '~/.config/gtk-3.0/gtk.css'

# Gtk4
[templates.gtk4]
input_path = '~/.config/matugen/templates/matugen-gtk.css'
output_path = '~/.config/gtk-4.0/gtk.css'
